### ISSUE TITLE
Link error: undefined reference to all functions when building test_filter

### ISSUE THREAD

**Issue by gustad** [xtrx-sdr/libxtrxdsp#2]
I've built the pcie driver and libxtrxll, but libxtrxdsp results in a linking error:

```
$git rev-parse --short HEAD
5dc9e4d
$mkdir build
$cd build
$cmake -DFORCE_ARCH=x86_64 -DCMAKE_INSTALL_PREFIX:PATH=$HOME/root ..
$make
Scanning dependencies of target xtrxdsp
[ 11%] Building C object CMakeFiles/xtrxdsp.dir/xtrxdsp.c.o
[ 22%] Building C object CMakeFiles/xtrxdsp.dir/xtrxdsp_filters.c.o
[ 33%] Building C object CMakeFiles/xtrxdsp.dir/xtrxdsp_filters_data.c.o
[ 44%] Building C object CMakeFiles/xtrxdsp.dir/xtrxdsp_no.c.o
[ 55%] Linking C shared library libxtrxdsp.so
[ 55%] Built target xtrxdsp
Scanning dependencies of target test_filter
[ 66%] Building C object tests/CMakeFiles/test_filter.dir/test_filter.c.o
[ 77%] Linking C executable test_filter
../libxtrxdsp.so.0.0.1: undefined reference to `xtrxdsp_iq16_ic16i_avx'
../libxtrxdsp.so.0.0.1: undefined reference to `xtrxdsp_iq16_ic16i_sse2'
../libxtrxdsp.so.0.0.1: undefined reference to `xtrxdsp_iq16_conv64_sse2'
...
../libxtrxdsp.so.0.0.1: undefined reference to `xtrxdsp_ic16i_iq16_avx'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_filter.dir/build.make:96: tests/test_filter] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: tests/CMakeFiles/test_filter.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

**Comment by mpbraendli** [comment]
I needed to change `CMakeLists.txt` to get it to work:

```diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2198183..346b153 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -78,7 +78,7 @@ set(GENERIC_TUNE "")
 include_directories(".")
 
 set(XTRX_DSP_FILES xtrxdsp.c xtrxdsp_filters.c xtrxdsp_filters_data.c xtrxdsp_no.c)
-if(ARCH STREQUAL "x86")
+if(ARCH STREQUAL "x86_64")
     set(XTRX_DSP_FILES ${XTRX_DSP_FILES}
                        xtrxdsp_x86_sse2.c
                        xtrxdsp_x86_avx.c
```

This is not a proper fix because it breaks `x86`. Also, the auto-detection using `-print-multiarch` is broken.

**Comment by mpbraendli** [comment]
Maybe the intention was to set `-DFORCE_ARCH=x86` rather than what I did. Try with that instead.

**Comment by sergforce** [comment]
Yes, the proper way is to use ``-DFORCE_ARCH=x86``. But you're right it's ambiguous for x86_64 target.
I'll incorporate this:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2198183..80f8333 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -78,7 +78,7 @@ set(GENERIC_TUNE "")
 include_directories(".")
 
 set(XTRX_DSP_FILES xtrxdsp.c xtrxdsp_filters.c xtrxdsp_filters_data.c xtrxdsp_no.c)

-if(ARCH STREQUAL "x86")
+if(ARCH MATCHES "^x86.*")
     set(XTRX_DSP_FILES ${XTRX_DSP_FILES}
                        xtrxdsp_x86_sse2.c
                        xtrxdsp_x86_avx.c
```

**Comment by mpbraendli** [comment]
Thank you. I patched CMakeLists to default to x86, because I didn't see how to pass the option when using the build procedure shown in the README in https://github.com/xtrx-sdr/images

Haven't been able yet to get the XTRX running, when I connect it over USB nothing gets enumerated on the host. I don't know if that's expected because the XTRX is not flashed yet, or if it is a problem.

I need to compile the kernel module on another machine, which has a mini-PCIe port.

**Comment by gustad** [comment]
Thanks. This worked for me:
```
-if(ARCH STREQUAL "x86")
+if(ARCH STREQUAL "x86" OR ARCH STREQUAL "x86_64")
```
Then:

```
cmake -DFORCE_ARCH=$(uname -m) ..
make
```
Testing the programs:

```
# ./test_xtrxdsp_sc32i_iq16 
Total errors: 0
# ./test_filter 
CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
Using avx_fma for xtrxdsp_sc32_conv64
```
And it just hangs indefinitely.

I don't know why cmake was not able to set CC_ARCH though.

**Comment by sergforce** [comment]
USB2 on XTRX itself isn't working, see https://github.com/xtrx-sdr/images/issues/9

./test_filter works differently. It expects data on stdin and produces filtered data on stdout. I.e. it can be used in FIFO or a pipe like style.

Detecting CC_ARCH is based on compiler meta info. Each Linux distribution makes it different so in some cases it won't work well

**Comment by sergforce** [comment]
update to master

feel free to reopen if any problem is discovered
